In [53]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

df = pd.read_csv("group_26_train.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (100000, 35)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,y
0,Source2,2018-03-30 17:32:46,40.810566,-73.256042,NaN,NaN,0.000,Commerce Dr,Hauppauge,Suffolk,NY,11788-3968,KISP,52.0,NaN,29.77,10.0,NNW,13.8,0.01,Overcast,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2
1,Source1,2022-07-27 13:42:00,45.358867,-122.762271,45.341362,-122.768971,1.252,I-5 S,Tualatin,Washington,OR,97062,KUAO,90.0,90.0,29.78,10.0,NNE,3.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
2,Source1,2022-06-06 13:00:30,41.233610,-95.954493,41.242050,-95.953603,0.585,US-75,Omaha,Douglas,NE,68105,KOMA,76.0,76.0,28.67,10.0,VAR,3.0,0.00,Mostly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
3,Source1,2021-09-07 21:50:00,34.039947,-117.505855,34.037156,-117.505860,0.193,Ranchero Dr,Fontana,San Bernardino,CA,92337,KONT,77.0,77.0,28.89,10.0,WSW,5.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
4,Source2,2019-05-23 20:52:35,47.230240,-122.448868,NaN,NaN,0.000,I-5 N,Tacoma,Pierce,WA,98418,KTCM,63.0,63.0,29.53,10.0,W,8.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,3

In [54]:
df.sample(5)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,y
4124,Source1,2020-04-23 15:34:11,35.353060,-80.845490,35.353060,-80.845490,0.000,I-77 N,Charlotte,Mecklenburg,NC,28269,KJQF,63.0,63.0,29.10,7.0,SSE,3.0,0.0,Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
20481,Source2,2019-08-06 13:24:19,45.057209,-93.187546,NaN,NaN,0.000,I-35W S,Saint Paul,Ramsey,MN,55112,KANE,82.0,82.0,28.89,10.0,NW,8.0,0.0,Partly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,3
88555,Source1,2022-10-02 19:18:00.000000000,34.121092,-118.271591,34.120317,-118.271191,0.058,Golden State Fwy S,Los Angeles,Los Angeles,CA,90027,KCQT,66.0,66.0,29.74,10.0,CALM,0.0,0.0,Fair,False,False,False,False,False,False,False,False,False,Night,Night,Day,Day,2
43876,Source2,2017-08-30 08:23:16,33.844017,-84.530380,NaN,NaN,0.000,Cooper Lake Rd SE,Smyrna,Cobb,GA,30082,KMGE,70.7,NaN,30.05,10.0,East,4.6,NaN,Overcast,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2
32809,Source1,2022-03-04 16:02:06,25.730293,-80.389931,25.729710,-80.399608,0.604,SW 42nd St,Miami,Miami-Dade,FL,33175,KTMB,81.0,81.0,30.14,10.0,E,18.0,0.0,Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 35 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   f1      100000 non-null  str
 1   f2      100000 non-null  str
 2   f3      100000 non-null  float64
 3   f4      100000 non-null  float64
 4   f5      55744 non-null   float64
 5   f6      55744 non-null   float64
 6   f7      100000 non-null  float64
 7   f8      99844 non-null   str
 8   f9      99998 non-null   str
 9   f10     100000 non-null  str
 10  f11     100000 non-null  str
 11  f12     99974 non-null   str
 12  f13     99716 non-null   str
 13  f14     97926 non-null   float64
 14  f15     74018 non-null   float64
 15  f16     98212 non-null   float64
 16  f17     97793 non-null   float64
 17  f18     97773 non-null   str
 18  f19     92625 non-null   float64
 19  f20     71369 non-null   float64
 20  f21     97818 non-null   str
 21  f22     100000 non-null  bool
 22  f23     100000 non-null  bool
 23  f24     100000 non-null  bool
 24  f25     100000 non-null  bool
 25  f26     100000 non-null  bool
 26  f27     100000 non-null  bool
 27  f28     100000 non-null  bool
 28  f29     100000 non-null  bool
 29  f30     100000 non-null  bool
 30  f31     99687 non-null   str
 31  f32     99687 non-null   str
 32  f33     99687 non-null   str
 33  f34     99687 non-null   str
 34  y       100000 non-null  int64
dtypes: bool(9), float64(11), int64(1), str(14)
memory usage: 20.7 MB

In [56]:
numeric_cols = [col for col in df.select_dtypes(include=[np.number]).columns if col != 'y']
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
bool_cols = df.select_dtypes(include=["bool"]).columns.tolist()

print("Numeric columns:", len(numeric_cols))
print(numeric_cols)

print("\nCategorical columns:", len(categorical_cols))
print(categorical_cols)

print("\nBoolean columns:", len(bool_cols))
print(bool_cols)

Numeric columns: 11
['f3', 'f4', 'f5', 'f6', 'f7', 'f14', 'f15', 'f16', 'f17', 'f19', 'f20']

Categorical columns: 14
['f1', 'f2', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f18', 'f21', 'f31', 'f32', 'f33', 'f34']

Boolean columns: 9
['f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30']

/tmp/ipykernel_31282/2905994014.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

In [57]:
missing_count = df.isnull().sum()
missing_percent = (missing_count / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percent": missing_percent
}).sort_values("Missing Percent", ascending=False)

missing_report

     Missing Count  Missing Percent
f5           44256           44.256
f6           44256           44.256
f20          28631           28.631
f15          25982           25.982
f19           7375            7.375
f18           2227            2.227
f17           2207            2.207
f21           2182            2.182
f14           2074            2.074
f16           1788            1.788
f31            313            0.313
f33            313            0.313
f32            313            0.313
f34            313            0.313
f13            284            0.284
f8             156            0.156
f12             26            0.026
f9               2            0.002
f1               0            0.000
f3               0            0.000
f2               0            0.000
f10              0            0.000
f11              0            0.000
f7               0            0.000
f4               0            0.000
f22              0            0.000
f23              0            0.000
f27              0            0.000
f26              0            0.000
f25              0            0.000
f24              0            0.000
f30              0            0.000
f29              0            0.000
f28              0            0.000
y                0            0.000

In [58]:
desc_stats = df[numeric_cols].describe().T

desc_stats["range"] = desc_stats["max"] - desc_stats["min"]

desc_stats

,count,mean,std,min,25%,50%,75%,max,range
f3,100000.0,36.188088,5.081102,24.599331,33.368866,35.801849,40.071363,48.974396,24.375065
f4,100000.0,-94.789912,17.391180,-124.493149,-117.237465,-87.905347,-80.365911,-68.370040,56.123109
f5,55744.0,36.265218,5.263918,24.669550,33.461822,36.162364,40.152109,48.972835,24.303285
f6,55744.0,-95.838090,18.076242,-124.450182,-117.739344,-88.468429,-80.266970,-68.358910,56.091272
f7,100000.0,0.566265,1.759484,0.000000,0.000000,0.027000,0.465000,112.903000,112.903000
f14,97926.0,61.687509,19.005531,-37.000000,49.000000,64.000000,76.000000,122.000000,159.000000
f15,74018.0,58.218894,22.399464,-52.200000,43.000000,62.000000,75.000000,114.000000,166.200000
f16,98212.0,29.532370,1.019610,19.750000,29.370000,29.850000,30.030000,58.390000,38.640000
f17,97793.0,9.085640,2.662043,0.000000,10.000000,10.000000,10.000000,80.000000,80.000000
f19,92625.0,7.674199,5.877039,0.000000,4.600000,7.000000,10.400000,812.000000,812.000000
f20,71369.0,0.008074,0.101830,0.000000,0.000000,0.000000,0.000000,9.990000,9.990000

In [59]:
skewness = df[numeric_cols].skew().sort_values(ascending=False)

skewness

f20    77.328223
f19    28.242046
f7     13.479845
f17     1.833843
f3     -0.055770
f5     -0.145489
f6     -0.352678
f4     -0.472218
f14    -0.505407
f15    -0.660922
f16    -3.350646
dtype: float64

In [60]:
outlier_counts = {}

for col in numeric_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = ((df[col] < lower) | (df[col] > upper)).sum()
    
    outlier_counts[col] = outliers

outlier_df = pd.DataFrame.from_dict(outlier_counts, orient="index", columns=["Outlier Count"])

outlier_df.sort_values("Outlier Count", ascending=False)

     Outlier Count
f17          19203
f7           12529
f20           6907
f16           5836
f19           2708
f14            625
f15            558
f5               0
f4               0
f3               0
f6               0

In [61]:
unique_counts = df.nunique().sort_values(ascending=False)

unique_counts

f2     99407
f3     90725
f4     90686
f6     51577
f5     51573
f12    36879
f8     32428
f9      6406
f7      6177
f13     1616
f10     1303
f16      873
f15      662
f14      599
f20      119
f21       80
f19       73
f11       49
f17       45
f18       24
y          4
f1         3
f22        2
f24        2
f25        2
f26        2
f23        2
f27        2
f28        2
f31        2
f29        2
f33        2
f32        2
f34        2
f30        1
dtype: int64

In [62]:
constant_cols = [col for col in df.columns if df[col].nunique() <= 1]

print("Constant columns:")
print(constant_cols)

Constant columns:
['f30']

In [63]:
near_constant = []

for col in df.columns:
    
    top_freq = df[col].value_counts(normalize=True).values[0]
    
    if top_freq > 0.95:
        near_constant.append(col)

print("Near constant features:")
print(near_constant)

Near constant features:
['f22', 'f23', 'f25', 'f26', 'f27', 'f28', 'f30']

In [64]:
target_counts = df["y"].value_counts()
target_ratio = df["y"].value_counts(normalize=True) * 100

target_df = pd.DataFrame({
    "Count": target_counts,
    "Percent": target_ratio
})

target_df

   Count  Percent
y
2  79560    79.56
3  16910    16.91
4   2670     2.67
1    860     0.86

In [65]:
duplicate_mask = df.duplicated()

duplicate_rows = df[duplicate_mask]

print("Number of duplicate rows:", duplicate_rows.shape[0])
duplicate_rows

Number of duplicate rows: 70

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,y
9445,Source1,2022-04-15 13:35:30,37.680321,-97.171329,37.679346,-97.166697,0.262,S 143rd St E,Wichita,Sedgwick,KS,67230,KAAO,73.0,73.0,28.25,10.00,W,6.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
15383,Source1,2018-09-18 16:16:12,28.019455,-82.758499,28.019455,-82.758499,0.000,Main St,Dunedin,Pinellas,FL,34698-4775,KPIE,88.0,NaN,29.92,10.00,Calm,NaN,NaN,Clear,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
16183,Source1,2021-04-03 08:09:00,38.729880,-120.796443,38.728182,-120.806941,0.578,US-50 W,Placerville,El Dorado,CA,95667,KPVF,57.0,57.0,27.41,10.00,ESE,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
16338,Source1,2022-04-18 13:01:00.000000000,41.091303,-78.517281,41.060413,-78.449411,4.129,I-80,Penfield,Clearfield,PA,15849,KFIG,33.0,26.0,28.50,4.00,ESE,8.0,0.01,Light Snow,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
17513,Source1,2020-12-14 09:48:06,39.492478,-75.042672,39.493065,-75.042620,0.041,W Park Ave,Vineland,Cumberland,NJ,08360,KMIV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2
18421,Source1,2022-01-10 17:29:02.000000000,35.843975,-78.680629,35.842775,-78.680237,0.086,Creedmoor Rd,Raleigh,Wake,NC,27612-3815,KRDU,40.0,40.0,29.83,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,2
18794,Source1,2022-02-09 12:00:07.000000000,40.524391,-74.345566,40.484811,-74.400036,3.958,New Jersey Tpke Cars Only Ln,Edison,Middlesex,NJ,08837,KLDJ,42.0,39.0,30.04,NaN,SSW,6.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
25134,Source1,2022-07-23 16:11:00.000000000,40.267424,-78.861442,40.262727,-78.870098,0.560,Eisenhower Blvd,Johnstown,Cambria,PA,15904-3327,KJST,83.0,83.0,27.71,10.00,WSW,9.0,0.00,Mostly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
27884,Source1,2021-10-05 15:39:30,28.522539,-81.314524,28.524317,-81.313584,0.135,Dixie Belle Dr,Orlando,Orange,FL,32812-8526,KORL,89.0,89.0,29.84,10.00,E,10.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
31093,Source1,2022-04-29 12:17:05,25.945914,-80.205394,25.942485,-80.204455,0.244,NW 2nd Ave,Miami,Miami-Dade,FL,33169-4508,KHWO,82.0,82.0,30.04,10.00,ESE,9.0,0.00,Mostly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
35459,Source2,2020-08-16 15:13:23,35.059372,-118.998909,NaN,NaN,0.000,I-5 N,Bakersfield,Kern,CA,93313,KBFL,102.0,102.0,29.33,10.00,W,6.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,3
37354,Source1,2022-04-19 08:51:48.000000000,28.201491,-80.670772,28.200079,-80.672074,0.126,Pineda Cswy,Melbourne,Brevard,FL,32940,KCOF,74.0,74.0,30.02,10.00,N,18.0,0.00,Partly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
37527,Source1,2022-12-27 14:16:29,43.983459,-121.607260,43.982956,-121.610906,0.185,Cascade Lakes Hwy,La Pine,Deschutes,OR,97739,KBDN,43.0,36.0,25.90,10.00,SW,14.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
40761,Source1,2022-03-22 21:07:29,41.158079,-104.338864,41.158629,-104.266664,3.756,US-30,Burns,Laramie,WY,82053,K82V,30.0,18.0,24.95,10.00,NW,17.0,NaN,Partly Cloudy,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
40851,Source1,2022-04-16 19:00:30,25.954534,-80.245846,25.955485,-80.247016,0.098,NW 27th Ave,Miami Gardens,Miami-Dade,FL,33056,KOPF,80.0,80.0,29.97,10.00,ESE,13.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
43422,Source1,2020-05-28 09:20:13,37.804320,-122.233310,37.804320,-122.233310,0.000,Park Blvd,Oakland,Alameda,CA,94610-2834,KOAK,60.0,60.0,29.94,10.00,NW,6.0,0.00,Cloudy,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,1
45091,Source1,2020-11-10 03:11:00,42.407527,-83.078280,42.396597,-83.068483,0.906,Chrysler Expy S,Highland Park,Wayne,MI,48203,KDET,65.0,65.0,29.34,10.00,SSW,10.0,0.00,Mostly Cloudy,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
47134,Source1,2022-07-28 18:21:00,32.988506,-117.075153,32.988539,-117.075260,0.007,Rancho Carmel Dr,San Diego,San Diego,CA,92128,KRNM,83.0,83.0,28.41,10.00,WNW,8.0,0.00,Fair,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2
49504,Source1,2022-01-24 17:16:44,28.464360,-81.274595,28.466792,-81.276349,0.199,Narcoossee Rd,Orlando,Orange,FL,32822-5532,KORL,61.0,61.0,29.86,10.00,WNW,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
50078,Source1,2021-07-06 12:51:23,25.622598,-80.414436,25.627069,-80.414418,0.309,Lingren Avenue Rd,Miami,Miami-Dade,FL,33177,KTMB,84.0,84.0,30.04,6.00,SSE,17.0,0.01,Rain,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2
50122,Source1,2020-06-28 13:44:00,40.626750,-74.243160,40.626750,-74.243160,0.000,E Edgar Rd,Linden,Union,NJ,07036-3262,KLDJ,NaN,NaN,29.70,10.00,W,3.0,0.00,Partly Cloudy,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2
51059,Source1,2020-12-09 03:45:00,37.381185,-76.759189,37.357125,-76.736709,2.071,I-64 E,Williamsburg,James City,VA,23188,KJGG,28.0,28.0,29.98,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
51426,Source1,2020-11-20 10:32:00,34.087454,-117.650839,34.087454,-117.655069,0.242,I-10,Upland,San Bernardino,CA,91786,KONT,72.0,72.0,29.08,10.00,SSW,3.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
51541,Source1,2022-06-06 06:36:30,28.437369,-81.404388,28.435928,-81.403545,0.112,S Orange Blossom Trl,Orlando,Orange,FL,32809-7912,KMCO,76.0,76.0,29.75,10.00,E,5.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
53167,Source1,2020-09-22 12:48:30,25.899721,-80.180184,25.900098,-80.178480,0.109,NE 135th St,North Miami,Miami-Dade,FL,33161-4129,KOPF,85.0,85.0,30.01,10.00,ENE,22.0,0.00,Fair / Windy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
53551,Source1,2022-04-20 09:47:30,35.117773,-80.922644,35.114745,-80.924273,0.229,I-77 S,Charlotte,Mecklenburg,NC,28273,KCLT,53.0,53.0,29.64,10.00,ESE,10.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
54525,Source1,2021-11-09 07:55:30,33.845972,-117.905264,33.848005,-117.905947,0.146,N East St,Anaheim,Orange,CA,92805-2135,KFUL,60.0,60.0,30.12,10.00,CALM,0.0,0.00,Mostly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
54936,Source1,2020-04-13 19:50:56,40.171030,-75.071220,40.171030,-75.071220,0.000,Davisville Rd,Huntingdon Valley,Montgomery,PA,19006,KPNE,70.0,70.0,29.59,10.00,W,18.0,0.00,Fair,False,False,False,False,False,False,False,True,False,Night,Day,Day,Day,2
56784,Source1,2020-10-14 04:06:06,40.868443,-74.003380,40.861983,-73.974700,1.564,New Jersey Tpke N,Teaneck,Bergen,NJ,07666,KTEB,46.0,44.0,29.91,10.00,SW,5.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
57920,Source1,2023-01-31 09:43:00.000000000,32.353612,-110.974588,32.353112,-110.974694,0.035,W Cool Dr,Tucson,Pima,AZ,85704,KDMA,51.0,51.0,27.22,10.00,SE,5.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
58519,Source1,2022-02-08 14:41:00,36.570449,-121.518553,36.571080,-121.517546,0.071,Grant St,Chualar,Monterey,CA,93925,KSNS,77.0,77.0,30.09,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,True,False,False,False,Day,Day,Day,Day,2
58591,Source1,2020-11-10 02:41:09,36.745351,-81.886543,36.755711,-81.862543,1.509,I-81 N,Abingdon,Washington,VA,24211,KVJI,59.0,59.0,27.99,10.00,ESE,6.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
59960,Source1,2021-07-10 18:11:00,34.206304,-117.108576,34.206632,-117.108517,0.023,Hilltop Blvd,Running Springs,San Bernardino,CA,92382,KSBD,97.0,97.0,28.64,7.00,W,13.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
60591,Source1,2022-05-20 14:27:23.000000000,25.684325,-80.416429,25.686252,-80.416521,0.133,SW 137th Ave,Miami,Miami-Dade,FL,33186,KTMB,91.0,91.0,30.01,10.00,SSW,15.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
60739,Source1,2020-10-01 11:58:00,37.552880,-77.443783,37.559623,-77.453129,0.692,N Belvidere St,Richmond,Richmond City,VA,23220,KRIC,75.0,75.0,29.78,10.00,W,7.0,0.00,Mostly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
60781,Source1,2020-11-10 13:09:30,41.950875,-122.590137,41.922735,-122.576627,2.065,I-5 S,Hornbrook,Siskiyou,CA,96044,KSIY,53.0,NaN,27.35,10.00,NaN,NaN,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
62565,Source1,2020-09-28 13:21:25,25.926748,-80.207082,25.927671,-80.204352,0.181,FL-7,Miami,Miami-Dade,FL,33169,KHWO,91.0,91.0,29.91,10.00,SSE,13.0,0.00,Fair,False,False,True,False,False,False,False,False,False,Day,Day,Day,Day,2
63300,Source1,2022-05-13 14:30:14,27.008705,-82.133227,27.007966,-82.135221,0.133,Cochran Blvd,Port Charlotte,Charlotte,FL,33948-20ND,KPGD,79.0,79.0,29.93,10.00,SE,13.0,0.00,Cloudy,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2
64348,Source1,2021-01-21 15:36:18,40.011445,-74.849649,40.009295,-74.851379,0.174,I-295 S,Mount Holly,Burlington,NJ,08060,KVAY,44.0,40.0,29.59,10.00,WSW,7.0,0.00,Fair,False,False,True,False,False,False,False,False,False,Day,Day,Day,Day,2
65955,Source1,2021-09-24 13:09:00,25.688012,-80.384015,25.686294,-80.384105,0.119,SW 117th Ave,Miami,Miami-Dade,FL,33183,KTMB,90.0,90.0,29.95,10.00,ESE,5.0,0.00,Mostly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
67626,Source1,2020-12-30 21:28:08,42.935201,-85.639613,42.934661,-85.639218,0.042,Kalamazoo Ave SE,Grand Rapids,Kent,MI,49507-2129,KGRR,30.0,17.0,28.98,10.00,W,22.0,0.00,Cloudy / Windy,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
67934,Source1,2021-10-29 14:53:00,38.612578,-121.415351,38.610783,-121.414425,0.134,Howe Ave,Sacramento,Sacramento,CA,95821-5520,KMCC,75.0,75.0,29.80,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
68428,Source1,2022-03-04 09:26:00,34.036329,-117.976837,34.035256,-117.973744,0.192,Valley Blvd,La Puente,Los Angeles,CA,91746-2919,KEMT,62.0,62.0,29.83,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
69230,Source1,2022-04-14 15:37:37,29.735734,-95.627702,29.736806,-95.623687,0.252,Westheimer Rd,Houston,Harris,TX,77077-3403,KSGR,84.0,84.0,29.89,10.00,ESE,13.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
70705,Source1,2020-12-13 18:51:00,36.457851,-118.880011,36.457787,-118.877432,0.143,Sierra Dr,Three Rivers,Tulare,CA,93271-9685,KVIS,52.0,52.0,29.87,10.00,E,7.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
73798,Source1,2021-08-27 17:03:51,40.706487,-74.061759,40.706212,-74.062285,0.033,I-78 W,Jersey City,Hudson,NJ,07305,KJRB,77.0,77.0,30.01,0.25,WNW,13.0,0.24,Heavy Rain,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
73866,Source1,2021-07-06 13:32:12,47.290722,-122.313557,47.289574,-122.311594,0.121,16th Ave S,Federal Way,King,WA,98003-8904,KSEA,71.0,71.0,29.55,10.00,W,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
76156,Source1,2022-10-12 08:19:00,40.823325,-73.821002,40.823895,-73.822189,0.074,Cross Bronx Expy Ext,Bronx,Bronx,NY,10465,KLGA,60.0,60.0,30.23,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
77136,Source1,2022-01-08 10:34:30,35.927876,-84.042885,35.926609,-84.043196,0.089,W Town Way,Knoxville,Knox,TN,37919,KTYS,30.0,30.0,29.41,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
77960,Source1,2022-03-09 12:29:05.000000000,27.820092,-82.728432,27.820975,-82.728985,0.070,66th St N,Saint Petersburg,Pinellas,FL,33709-3125,KPIE,82.0,82.0,29.95,10.00,SSW,21.0,0.00,Cloudy / Windy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
78137,Source1,2022-10-31 20:36:30,28.146217,-81.464520,28.143215,-81.470059,0.396,Cypress Pkwy,Kissimmee,Osceola,FL,34758,KISM,77.0,77.0,29.92,10.00,E,7.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
78209,Source1,2020-10-16 12:05:30,25.749454,-80.335813,25.747587,-80.335122,0.136,SW 87th Ave,Miami,Miami-Dade,FL,33165-2090,KMIA,85.0,85.0,30.00,10.00,E,10.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
78380,Source1,2021-12-04 15:22:30,38.704969,-77.224142,38.641311,-77.288339,5.598,I-95 S,Lorton,Fairfax County,VA,22079,KDAA,60.0,60.0,30.00,10.00,WNW,8.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
78573,Source1,2020-10-19 20:24:30,39.445906,-87.243643,39.430046,-87.306713,3.539,I-70 W,Terre Haute,Vigo,IN,47803,KHUF,52.0,52.0,29.50,10.00,NE,6.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day,2
81133,Source1,2022-02-25 14:55:30,34.055571,-118.198100,34.055190,-118.211842,0.787,I-10 W,Los Angeles,Los Angeles,CA,90033,KCQT,61.0,61.0,29.94,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
81819,Source1,2021-12-29 12:39:06,34.502024,-82.686188,34.501312,-82.683707,0.150,W Whitner St,Anderson,Anderson,SC,29626-1030,KAND,67.0,67.0,29.07,10.00,SSW,9.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
82693,Source1,2021-01-13 01:08:06,45.619622,-120.739113,45.647352,-120.808583,3.865,Highway 97,Wasco,Sherman,OR,97065-3039,KDLS,45.0,45.0,29.42,2.00,CALM,0.0,0.02,Light Rain,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
82882,Source1,2021-11-20 11:05:00,37.549002,-77.115202,37.549929,-77.114263,0.082,Griffith Cir,New Kent,New Kent,VA,23124,KFYJ,47.0,47.0,30.54,10.00,SSE,3.0,0.00,NaN,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
83810,Source1,2020-10-02 12:21:00,25.732181,-80.379671,25.733374,-80.383242,0.237,SW 40th St,Miami,Miami-Dade,FL,33165-3311,KMIA,83.0,83.0,29.93,10.00,NE,5.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
85202,Source1,2022-06-22 13:06:19.000000000,41.546706,-86.739945,41.568187,-86.739480,1.484,S State Road 39,La Porte,Laporte,IN,46350-9218,KPPO,81.0,81.0,29.21,10.00,NNW,12.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
85217,Source1,2019-09-16 09:29:00,34.585346,-118.709771,34.590479,-118.711634,0.370,Golden State Fwy N,Castaic,Los Angeles,CA,91384,K3A6,76.0,76.0,29.08,10.00,S,8.0,0.00,Partly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,3
89138,Source1,2021-08-07 13:06:24,39.074239,-76.906518,39.074889,-76.905438,0.073,MD-200 W,Beltsville,Prince George's,MD,20705,KCGS,72.0,72.0,30.04,7.00,S,3.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
89731,Source1,2020-10-27 03:24:00,32.958786,-86.743474,32.958382,-86.743347,0.029,US Highway 31,Jemison,Chilton,AL,35085-4436,KEET,66.0,66.0,29.47,6.00,NE,3.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night,2
89988,Source1,2022-12-18 12:40:10,40.974648,-73.707293,40.975260,-73.713146,0.308,New England Trwy S,Harrison,Westchester,NY,10528,KHPN,38.0,30.0,29.38,10.00,WNW,13.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
91450,Source1,2021-11-22 19:03:54,47.357321,-102.641801,47.352893,-102.631884,0.556,Highway 200,Dunn Center,Dunn,ND,58626,KDIK,35.0,27.0,27.15,10.00,S,10.0,0.00,Fair,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,2
91564,Source1,2020-11-30 17:26:49,39.222934,-76.720036,39.234749,-76.710539,0.962,I-95 N,Elkridge,Howard,MD,21075,KBWI,62.0,62.0,29.20,10.00,WSW,9.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Night,Night,Day,Day,2
92802,Source1,2020-11-18 12:58:30,37.826428,-122.300534,37.823738,-122.318829,1.016,I-80 W,Oakland,Alameda,CA,94607,KOAK,65.0,65.0,30.07,10.00,SW,12.0,0.00,Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
95642,Source1,2020-12-07 14:50:30,43.619530,-116.351918,43.618685,-116.354611,0.147,E Fairview Ave,Meridian,Ada,ID,83646,KMAN,41.0,41.0,27.85,10.00,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
98132,Source1,2018-12-10 15:41:04,35.181490,-80.776670,35.181490,-80.776670,0.000,N Sharon Amity Rd,Charlotte,Mecklenburg,NC,28211-3194,KCLT,41.0,39.0,30.11,10.00,North,3.5,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2
98431,Source1,2021-01-03 22:48:51,29.902092,-97.903965,29.926282,-97.890895,1.846,I-35 N,San Marcos,Hays,TX,78666,KHYI,47.0,44.0,29.41,10.00,SSW,6.0,0.00,Fair,False,False,True,False,False,False,False,False,False,Night,Night,Night,Night,2

In [66]:
zero_counts = (df[numeric_cols] == 0).sum().sort_values(ascending=False)

zero_counts

f20    64462
f7     43052
f19    12433
f17      103
f15       53
f14       30
f3         0
f5         0
f4         0
f6         0
f16        0
dtype: int64

<div dir="rtl" align="right">

## ۱.۴ شناخت داده (Data Understanding)

### داده شامل چه ستون‌ها یا ویژگی‌هایی است؟
این مجموعه‌داده شامل **۱۰۰,۰۰۰ نمونه و ۳۵ ستون** می‌باشد. ویژگی‌ها را می‌توان به صورت زیر دسته‌بندی کرد:

- **ویژگی‌های زمانی و شناسایی:**  
  شامل ستون منبع داده (`f1`) و زمان ثبت رویداد (`f2`).

- **مختصات جغرافیایی:**  
  ویژگی‌های عددی (`f3` تا `f6`) که عرض و طول جغرافیایی محل وقوع رویداد را نشان می‌دهند.

- **اطلاعات مکانی و آدرس:**  
  ویژگی‌های متنی یا دسته‌ای (`f8` تا `f12`) شامل خیابان، شهر، شهرستان، ایالت و کد پستی.

- **سنجش‌های محیطی و عددی:**  
  متغیرهای عددی (`f7` و `f14` تا `f18` و `f20`) که اندازه‌گیری‌های محیطی یا فیزیکی را نشان می‌دهند، به همراه ویژگی‌های دسته‌ای مرتبط (`f13`، `f19`، `f21`).

- **ویژگی‌های دوحالتی (Boolean):**  
  ستون‌های (`f22` تا `f34`) که مقدار True/False دارند و وجود یا عدم وجود برخی شرایط یا ویژگی‌های مکانی را مشخص می‌کنند.

- **متغیر هدف:**  
  ستون نهایی با نام `y`.

### هر نمونه نشان‌دهنده چیست؟
هر ردیف از داده نشان‌دهنده **ثبت یک رویداد واحد** در یک زمان و مکان مشخص است.  
این رکورد ترکیبی از اطلاعات زمانی، مکانی، محیطی و شرایط مرتبط با آن رویداد را ارائه می‌دهد.

### هدف پروژه بر اساس این داده چیست؟
هدف پروژه، **ساخت یک مدل پیش‌بینی‌کننده** است که بتواند با استفاده از ویژگی‌های موجود، کلاس مربوط به هر رویداد را پیش‌بینی کند (ستون `y`).

### متغیر هدف کدام است؟
متغیر هدف ستون **`y`** است که یک متغیر **دسته‌ای با ۴ کلاس (۱، ۲، ۳ و ۴)** می‌باشد.

### نوع مسئله چیست؟
با توجه به اینکه داده‌ها دارای برچسب هستند و هدف پیش‌بینی یک متغیر دسته‌ای است، این مسئله از نوع **یادگیری نظارت‌شده (Supervised Learning)** و به طور خاص **طبقه‌بندی چندکلاسه (Multi-class Classification)** می‌باشد.

</div>