In [752]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [753]:
df = pd.read_csv("group_26_train.csv")

print("Shape of dataset:", df.shape)
df.head()

Shape of dataset: (100000, 35)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f26,f27,f28,f29,f30,f31,f32,f33,f34,y
0,Source2,2018-03-30 17:32:46,40.810566,-73.256042,NaN,NaN,0.000,Commerce Dr,Hauppauge,Suffolk,...,False,False,False,True,False,Day,Day,Day,Day,2
1,Source1,2022-07-27 13:42:00,45.358867,-122.762271,45.341362,-122.768971,1.252,I-5 S,Tualatin,Washington,...,False,False,False,False,False,Day,Day,Day,Day,2
2,Source1,2022-06-06 13:00:30,41.233610,-95.954493,41.242050,-95.953603,0.585,US-75,Omaha,Douglas,...,False,False,False,False,False,Day,Day,Day,Day,2
3,Source1,2021-09-07 21:50:00,34.039947,-117.505855,34.037156,-117.505860,0.193,Ranchero Dr,Fontana,San Bernardino,...,False,False,False,False,False,Night,Night,Night,Night,2
4,Source2,2019-05-23 20:52:35,47.230240,-122.448868,NaN,NaN,0.000,I-5 N,Tacoma,Pierce,...,False,False,False,False,False,Night,Day,Day,Day,3

In [754]:
missing_values = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Count": missing_values,
    "Missing Percent": missing_percent
})

missing_table = missing_table[missing_table["Missing Count"] > 0]

missing_table = missing_table.sort_values("Missing Percent", ascending=False)

missing_table

     Missing Count  Missing Percent
f5           44256           44.256
f6           44256           44.256
f20          28631           28.631
f15          25982           25.982
f19           7375            7.375
f18           2227            2.227
f17           2207            2.207
f21           2182            2.182
f14           2074            2.074
f16           1788            1.788
f31            313            0.313
f32            313            0.313
f33            313            0.313
f34            313            0.313
f13            284            0.284
f8             156            0.156
f12             26            0.026
f9               2            0.002

In [755]:
original_rows = len(df)

df.drop_duplicates(inplace=True)

print("Removed rows:", original_rows - len(df))
print("New shape:", df.shape)

Removed rows: 70
New shape: (99930, 35)

In [756]:
row_threshold = 0.2

df = df.dropna(thresh=int((1 - row_threshold) * df.shape[1]))

print("Shape after removing highly-missing rows:", df.shape)

Shape after removing highly-missing rows: (98303, 35)

In [757]:
low_nan_cols = [col for col in df.columns if 0 < df[col].isnull().mean() < 0.05]

df.dropna(subset=low_nan_cols, inplace=True)

print("Shape after removing rows with small NaN columns:", df.shape)

Shape after removing rows with small NaN columns: (96209, 35)

In [758]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
bool_cols = df.select_dtypes(include=["bool"]).columns.tolist()

print("Numeric columns:", len(numeric_cols))
print(numeric_cols)

print("\nCategorical columns:", len(categorical_cols))
print(categorical_cols)

print("\nBoolean columns:", len(bool_cols))
print(bool_cols)

Numeric columns: 12
['f3', 'f4', 'f5', 'f6', 'f7', 'f14', 'f15', 'f16', 'f17', 'f19', 'f20', 'y']

Categorical columns: 14
['f1', 'f2', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f18', 'f21', 'f31', 'f32', 'f33', 'f34']

Boolean columns: 9
['f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30']

/tmp/ipykernel_21947/1539792205.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

In [759]:
missing_values = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Count": missing_values,
    "Missing Percent": missing_percent
})

missing_table = missing_table[missing_table["Missing Count"] > 0]

missing_table = missing_table.sort_values("Missing Percent", ascending=False)

missing_table

     Missing Count  Missing Percent
f5           43032        44.727624
f6           43032        44.727624
f20          26583        27.630471
f15          23103        24.013346
f19           4903         5.096197

In [760]:
corr_3_5 = df['f3'].corr(df['f5'])
corr_4_6 = df['f4'].corr(df['f6'])
corr_14_15 = df['f14'].corr(df['f15'])

print(f"Correlation between f3 and f5: {corr_3_5:.4f}")
print(f"Correlation between f4 and f6: {corr_4_6:.4f}")
print(f"Correlation between f14 and f15: {corr_14_15:.4f}")

df.drop(columns=['f5', 'f6', 'f15'], inplace=True)

print("\nColumns 'f5', 'f6', and 'f15' have been dropped.")
print("Current columns in dataframe:", df.columns.tolist())

Correlation between f3 and f5: 1.0000
Correlation between f4 and f6: 1.0000
Correlation between f14 and f15: 0.9938

Columns 'f5', 'f6', and 'f15' have been dropped.
Current columns in dataframe: ['f1', 'f2', 'f3', 'f4', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'y']

In [761]:
missing_values = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Count": missing_values,
    "Missing Percent": missing_percent
})

missing_table = missing_table[missing_table["Missing Count"] > 0]

missing_table = missing_table.sort_values("Missing Percent", ascending=False)

missing_table

     Missing Count  Missing Percent
f20          26583        27.630471
f19           4903         5.096197

In [762]:
cols = ['f19', 'f20']

print("Shape:", df[cols].shape)

print("\nMissing values:")
print(df[cols].isna().sum())

print("\nMissing percentage:")
print(df[cols].isna().mean() * 100)

print("\nDescriptive statistics:")
print(df[cols].describe())

print("\nCorrelation:")
print(df[cols].corr())

Shape: (96209, 2)

Missing values:
f19     4903
f20    26583
dtype: int64

Missing percentage:
f19     5.096197
f20    27.630471
dtype: float64

Descriptive statistics:
                f19           f20
count  91306.000000  69626.000000
mean       7.681475      0.007846
std        5.881957      0.087900
min        0.000000      0.000000
25%        4.600000      0.000000
50%        7.000000      0.000000
75%       10.400000      0.000000
max      812.000000      9.990000

Correlation:
          f19       f20
f19  1.000000  0.032545
f20  0.032545  1.000000

In [763]:
from sklearn.feature_selection import mutual_info_classif

X = df[['f19','f20']]
y = df['y']

X = X.fillna(X.median())

mi = mutual_info_classif(X, y)

for col, score in zip(X.columns, mi):
    print(f"{col}: {score}")

f19: 0.02733052078582121
f20: 0.0027270360753999245

In [764]:
df['f19'] = df['f19'].fillna(df['f19'].median())

df.drop(columns=['f20'], inplace=True)

print("f19 missing values filled with median and f20 dropped.")
print("Current columns:", df.columns.tolist())

f19 missing values filled with median and f20 dropped.
Current columns: ['f1', 'f2', 'f3', 'f4', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f16', 'f17', 'f18', 'f19', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'y']

In [765]:
if 'f2' in df.columns:
    
    df['f2'] = pd.to_datetime(df['f2'], errors='coerce')

    df['hour'] = df['f2'].dt.hour
    df['dayofweek'] = df['f2'].dt.dayofweek
    df['month'] = df['f2'].dt.month
    df['day'] = df['f2'].dt.day

    df.drop('f2', axis=1, inplace=True)

print("Date features created.")

Date features created.

In [766]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
bool_cols = df.select_dtypes(include=["bool"]).columns.tolist()

print("Numeric columns:", len(numeric_cols))
print(numeric_cols)

print("\nCategorical columns:", len(categorical_cols))
print(categorical_cols)

print("\nBoolean columns:", len(bool_cols))
print(bool_cols)

Numeric columns: 12
['f3', 'f4', 'f7', 'f14', 'f16', 'f17', 'f19', 'y', 'hour', 'dayofweek', 'month', 'day']

Categorical columns: 13
['f1', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f18', 'f21', 'f31', 'f32', 'f33', 'f34']

Boolean columns: 9
['f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30']

/tmp/ipykernel_21947/1539792205.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

In [767]:
cat_cols = ['f1', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f18', 'f21', 'f31', 'f32', 'f33', 'f34']

summary = []

for col in cat_cols:
    summary.append({
        "column": col,
        "n_unique": df[col].nunique(),
        "top_category": df[col].mode().iloc[0] if not df[col].mode().empty else None,
        "top_freq": df[col].value_counts().iloc[0] if not df[col].value_counts().empty else None
    })

summary_df = pd.DataFrame(summary)

print("===== CATEGORICAL SUMMARY =====")
print(summary_df.sort_values("n_unique", ascending=False))

print("\n===== SAMPLE DISTRIBUTION =====")
for col in cat_cols:
    print(f"\n{col}")
    print(df[col].value_counts().head(10))

print("\n===== RELATIONSHIP WITH TARGET (y) =====")
for col in cat_cols:
    print(f"\n{col}")
    print(pd.crosstab(df[col], df['y'], normalize='index').head())

===== CATEGORICAL SUMMARY =====
   column  n_unique top_category  top_freq
5     f12     35794        91761       139
1      f8     31495       I-95 N      1008
2      f9      6139        Miami      2285
6     f13      1563         KCQT      1496
3     f10      1254  Los Angeles      6531
8     f21        79         Fair     32366
4     f11        49           CA     21757
7     f18        24         CALM     12203
0      f1         3      Source1     53177
9     f31         2          Day     66586
10    f32         2          Day     71142
11    f33         2          Day     76084
12    f34         2          Day     79783

===== SAMPLE DISTRIBUTION =====

f1
f1
Source1    53177
Source2    41797
Source3     1235
Name: count, dtype: int64

f8
f8
I-95 N     1008
I-95 S      890
I-5 N       856
I-10 W      699
I-5 S       667
I-10 E      653
I-80 E      474
I-80 W      467
I-405 N     422
I-75 N      363
Name: count, dtype: int64

f9
f9
Miami          2285
Houston        2186
Los Angeles    2011
Charlotte      1731
Dallas         1730
Orlando        1416
Austin         1261
Raleigh        1108
Baton Rouge     969
Nashville       933
Name: count, dtype: int64

f10
f10
Los Angeles       6531
Miami-Dade        3087
Orange            3074
Harris            2346
Dallas            2081
Mecklenburg       1831
Montgomery        1667
Wake              1557
Travis            1396
San Bernardino    1354
Name: count, dtype: int64

f11
f11
CA    21757
FL    10996
TX     7526
SC     4720
NY     4339
NC     4225
PA     3743
VA     3609
MN     2432
OR     2182
Name: count, dtype: int64

f12
f12
91761    139
91706    136
92407    123
92507    122
33186    113
90023    105
91403     98
32819     94
33169     94
91765     91
Name: count, dtype: int64

f13
f13
KCQT    1496
KRDU    1408
KMCJ    1304
KBNA    1234
KCLT    1214
KORL    1074
KBTR    1060
KMIA    1008
KDAL     928
KEMT     893
Name: count, dtype: int64

f18
f18
CALM    12203
S        5360
W        4948
SSW      4912
WNW      4886
Calm     4727
SW       4716
NW       4710
WSW      4596
SSE      4388
Name: count, dtype: int64

f21
f21
Fair                32366
Mostly Cloudy       12952
Clear               10387
Cloudy              10282
Partly Cloudy        8870
Overcast             4996
Light Rain           4618
Scattered Clouds     2673
Light Snow           1681
Fog                  1270
Name: count, dtype: int64

f31
f31
Day      66586
Night    29623
Name: count, dtype: int64

f32
f32
Day      71142
Night    25067
Name: count, dtype: int64

f33
f33
Day      76084
Night    20125
Name: count, dtype: int64

f34
f34
Day      79783
Night    16426
Name: count, dtype: int64

===== RELATIONSHIP WITH TARGET (y) =====

f1
y               1         2         3         4
f1
Source1  0.006582  0.912124  0.038043  0.043252
Source2  0.009929  0.653372  0.332440  0.004259
Source3  0.046154  0.620243  0.331174  0.002429

f8
y               1    2    3    4
f8
100th Ave SE  0.0  1.0  0.0  0.0
102nd Ave     0.0  1.0  0.0  0.0
104th Ave E   0.0  1.0  0.0  0.0
108th St      0.0  1.0  0.0  0.0
108th St E    0.0  1.0  0.0  0.0

f9
y              1         2         3       4
f9
Abbeville    0.0  1.000000  0.000000  0.0000
Abbotsford   0.0  1.000000  0.000000  0.0000
Abbottstown  0.0  1.000000  0.000000  0.0000
Aberdeen     0.0  0.947368  0.052632  0.0000
Abingdon     0.0  0.562500  0.375000  0.0625

f10
y            1         2         3         4
f10
Abbeville  0.0  1.000000  0.000000  0.000000
Acadia     0.0  0.750000  0.250000  0.000000
Accomack   0.0  0.428571  0.285714  0.285714
Ada        0.0  1.000000  0.000000  0.000000
Adair      0.0  1.000000  0.000000  0.000000

f11
y           1         2         3         4
f11
AL   0.007154  0.748808  0.223370  0.020668
AR   0.003509  0.821053  0.056140  0.119298
AZ   0.042115  0.823584  0.105288  0.029013
CA   0.006067  0.827642  0.158891  0.007400
CO   0.010093  0.592094  0.308663  0.089151

f12
y             1    2    3    4
f12
01005-9557  0.0  1.0  0.0  0.0
01007-9301  0.0  1.0  0.0  0.0
01010       0.0  0.0  1.0  0.0
01020       0.0  1.0  0.0  0.0
01033       0.0  1.0  0.0  0.0

f13
y       1         2         3         4
f13
K04W  0.0  0.846154  0.153846  0.000000
K0A9  0.0  0.500000  0.000000  0.500000
K0CO  0.0  0.517241  0.275862  0.206897
K0E0  0.0  0.500000  0.500000  0.000000
K0J4  0.0  1.000000  0.000000  0.000000

f18
y            1         2         3         4
f18
CALM  0.010899  0.869622  0.093174  0.026305
Calm  0.000000  0.654961  0.314364  0.030675
E     0.011348  0.861844  0.105248  0.021560
ENE   0.005659  0.795662  0.173216  0.025464
ESE   0.007523  0.803530  0.162616  0.026331

f21
y                            1         2         3         4
f21
Blowing Dust          0.000000  1.000000  0.000000  0.000000
Blowing Dust / Windy  0.000000  1.000000  0.000000  0.000000
Blowing Snow          0.000000  0.700000  0.300000  0.000000
Blowing Snow / Windy  0.000000  1.000000  0.000000  0.000000
Clear                 0.000193  0.662559  0.304323  0.032926

f31
y             1         2         3         4
f31
Day    0.009972  0.791818  0.176058  0.022152
Night  0.005334  0.805286  0.155420  0.033960

f32
y             1         2         3         4
f32
Day    0.009938  0.791642  0.176309  0.022111
Night  0.004588  0.808234  0.150955  0.036223

f33
y             1         2         3         4
f33
Day    0.009634  0.791678  0.176437  0.022252
Night  0.004422  0.812174  0.144248  0.039155

f34
y             1         2         3         4
f34
Day    0.009576  0.791647  0.176203  0.022574
Night  0.003531  0.816937  0.138135  0.041398

In [768]:
high_card = ['f12','f8','f9','f13','f10']
low_card = ['f21','f11','f18','f1','f31','f32','f33','f34']

for col in high_card:
    freq = df[col].value_counts() / len(df)
    df[col] = df[col].map(freq)

df = pd.get_dummies(df, columns=low_card, drop_first=True)

print("Encoding complete")
print("New shape:", df.shape)

Encoding complete
New shape: (96209, 181)

In [769]:
for col in high_card:
    if col in df.columns:
        freq = df[col].value_counts() / len(df)
        df[col] = df[col].map(freq)

existing_low_card = [c for c in low_card if c in df.columns]

df = pd.get_dummies(df, columns=existing_low_card, drop_first=True)

bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

print("Encoding complete")
print("New shape:", df.shape)

Encoding complete
New shape: (96209, 181)

In [770]:
print(df.shape)
df.head()

(96209, 181)

,f3,f4,f7,f8,f9,f10,f12,f13,f14,f16,...,f18_W,f18_WNW,f18_WSW,f18_West,f1_Source2,f1_Source3,f31_Night,f32_Night,f33_Night,f34_Night
0,40.810566,-73.256042,0.000,0.026879,0.011496,0.020663,0.285140,0.004365,52.0,29.77,...,0,0,0,0,1,0,0,0,0,0
1,45.358867,-122.762271,1.252,0.006933,0.005893,0.005083,0.007577,0.003014,90.0,29.78,...,0,0,0,0,0,0,0,0,0,0
2,41.233610,-95.954493,0.585,0.219636,0.002754,0.005062,0.008835,0.007276,76.0,28.67,...,0,0,0,0,0,0,0,0,0,0
3,34.039947,-117.505855,0.193,0.219636,0.002640,0.014074,0.018086,0.004792,77.0,28.89,...,0,0,1,0,0,0,1,1,1,1
4,47.230240,-122.448868,0.000,0.008897,0.001226,0.002183,0.021412,0.001195,63.0,29.53,...,1,0,0,0,1,0,1,0,0,0

In [771]:
X = df.drop("y", axis=1)
y = df["y"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (96209, 180)
Target shape: (96209,)

In [772]:
print("Target column:", 'y')
print("\nTotal rows:", len(df))

print("\nClass counts:")
print(df['y'].value_counts().sort_index())

print("\nClass percentages:")
print((df['y'].value_counts(normalize=True).sort_index() * 100).round(3))

print("\nNumber of classes:", df['y'].nunique())

print("\nMissing values in y:")
print(df['y'].isna().sum())

summary = pd.DataFrame({
    "count": df['y'].value_counts().sort_index(),
    "percent": (df['y'].value_counts(normalize=True).sort_index()*100).round(3)
})

print("\nSummary table:")
print(summary)

print("\nSuggested test sizes to consider:")
print("0.2 (standard)")
print("0.25 (safer for evaluation)")
print("0.3 (if dataset very large)")

Target column: y

Total rows: 96209

Class counts:
y
1      822
2    76579
3    16327
4     2481
Name: count, dtype: int64

Class percentages:
y
1     0.854
2    79.597
3    16.970
4     2.579
Name: proportion, dtype: float64

Number of classes: 4

Missing values in y:
0

Summary table:
   count  percent
y
1    822    0.854
2  76579   79.597
3  16327   16.970
4   2481    2.579

Suggested test sizes to consider:
0.2 (standard)
0.25 (safer for evaluation)
0.3 (if dataset very large)

In [773]:
from sklearn.model_selection import train_test_split

X = df.drop(columns='y')
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

print("\nTrain class distribution (%):")
print((y_train.value_counts(normalize=True).sort_index()*100).round(3))

print("\nTest class distribution (%):")
print((y_test.value_counts(normalize=True).sort_index()*100).round(3))

Train shape: (76967, 180)
Test shape: (19242, 180)

Train class distribution (%):
y
1     0.855
2    79.596
3    16.970
4     2.579
Name: proportion, dtype: float64

Test class distribution (%):
y
1     0.852
2    79.597
3    16.973
4     2.578
Name: proportion, dtype: float64

In [774]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_final = pd.DataFrame(X_train_scaled, columns=X.columns)
X_test_final = pd.DataFrame(X_test_scaled, columns=X.columns)

print("Data ready for modeling")
X_train_final.head()

Data ready for modeling

,f3,f4,f7,f8,f9,f10,f12,f13,f14,f16,...,f18_W,f18_WNW,f18_WSW,f18_West,f1_Source2,f1_Source3,f31_Night,f32_Night,f33_Night,f34_Night
0,0.124430,-1.444342,-0.294055,1.788577,-1.021818,-0.532641,1.575203,-0.463833,-0.932122,-0.036682,...,-0.231188,-0.230126,-0.223251,-0.14888,-0.875971,-0.115023,-0.668555,-0.595623,-0.51685,-0.455995
1,1.237792,0.664381,-0.326951,-0.725600,0.101760,-0.503841,-0.600675,0.187821,-1.881218,-0.273897,...,-0.231188,-0.230126,-0.223251,-0.14888,1.141591,-0.115023,1.495763,1.678915,-0.51685,-0.455995
2,0.008246,-1.432931,-0.326951,-0.086015,-0.402431,-0.606173,1.575203,-0.999230,0.275338,0.417981,...,-0.231188,-0.230126,-0.223251,-0.14888,1.141591,-0.115023,-0.668555,-0.595623,-0.51685,-0.455995
3,-0.190967,0.803131,-0.326951,-0.769153,1.485779,0.341162,-0.600675,2.176437,0.865887,0.526705,...,-0.231188,-0.230126,-0.223251,-0.14888,-0.875971,8.693910,-0.668555,-0.595623,-0.51685,-0.455995
4,0.700067,-0.586319,-0.326951,0.279288,-0.711290,-0.605560,-0.600675,-0.567853,-1.933946,-5.186232,...,-0.231188,-0.230126,-0.223251,-0.14888,1.141591,-0.115023,-0.668555,-0.595623,-0.51685,-0.455995